export const cities = [
    // A
    {name: 'Agadir'},
    // B
    {name: 'Beni Mellal'},
    {name: 'Berrechid'},
    {name: 'Bouznika'},
    // C
    {name: 'Casablanca'},
    {name: 'Chefchaouen'},
    // D
    {name: 'Dakhla'},
    {name: 'Demnate'},
    // E
    {name: 'El Jadida'},
    {name: 'Errachidia'},
    {name: 'Essaouira'},
    // F
    {name: 'Fès'},
    // G
    {name: 'Guelmim'},
    // H
    // I
    {name: 'Ifrane'},
    {name: 'Inezgane'},
    // J
    // K
    {name: 'Kénitra'},
    {name: 'Khémisset'},
    // L
    {name: 'Laâyoune'},
    // M
    {name: 'Marrakech'},
    {name: 'Meknès'},
    {name: 'Mohammédia'},
    // N
    {name: 'Nador'},
    // O
    {name: 'Ouarzazate'},
    {name: 'Oujda'},
    // P
    // Q
    // R
    {name: 'Rabat'},
    // S
    {name: 'Safi'},
    {name: 'Salé'},
    {name: 'Sefrou'},
    {name: 'Settat'},
    // T
    {name: 'Tanger'},
    {name: 'Tan-Tan'},
    {name: 'Taroudannt'},
    {name: 'Taza'},
    {name: 'Temara'},
    {name: 'Tétouan'},
    {name: 'Tiznit'},
    // U
    // V
    // W
    // X
    // Y
    {name: 'Youssoufia'},
    // Z
    {name: 'Zagora'},
    {name: 'Zag'}
]
